name: chewie_example
description: An example of how to use the chewie for Flutter
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  chewie:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:

  uses-material-design: true

