name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.7.1
homepage: https://github.com/fluttercommunity/chewie

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  cupertino_icons: any
  flutter:
    sdk: flutter
  provider: any
  video_player: any
  wakelock_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
